const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const context={navigator:{},window:{isSecureContext:true},Uint8Array,DataView,Date,setTimeout,clearTimeout};vm.createContext(context);vm.runInContext(fs.readFileSync('bosch-ble.js','utf8')+';globalThis.api={boschCrc8,boschSyncCommand,BoschFrameReader,boschDistancePayload,BoschDistanceLink,BOSCH_BLE_PROFILES}',context);
const {boschCrc8, BoschFrameReader, boschDistancePayload, BoschDistanceLink, BOSCH_BLE_PROFILES}=context.api;
assert.deepEqual(Array.from(context.api.boschSyncCommand(true)),[0xc0,0x55,2,1,0,0x1a]);assert.deepEqual(Array.from(context.api.boschSyncCommand(false)),[0xc0,0x55,2,0,0,0x62]);
function payload(metres=3.6505,mode=1,id=0x1234,status=0){const b=new Uint8Array(16),v=new DataView(b.buffer);b[0]=(mode<<2)|2;b[1]=status;v.setUint16(2,id,true);v.setFloat32(4,metres,true);return b}
function frame(data){const b=Uint8Array.of(0xc0,0x55,data.length,...data);return Uint8Array.of(...b,boschCrc8(b))}
const frames=[],issues=[],reader=new BoschFrameReader(f=>frames.push(f),e=>issues.push(e));const measured=frame(payload());reader.push(new DataView(measured.buffer,0,7));assert.equal(frames.length,0);reader.push(new DataView(measured.buffer,7));assert.equal(frames.length,1);const parsed=boschDistancePayload(frames[0].payload);assert.equal(parsed.id,0x1234);assert.equal(parsed.reference,2);assert(Math.abs(parsed.metres-3.6505)<.000001);
reader.reset();reader.push(new DataView(Uint8Array.of(...measured,...measured).buffer));assert.equal(frames.length,3);
const bad=measured.slice();bad[10]^=1;reader.reset();reader.push(new DataView(bad.buffer));assert.equal(frames.length,3);assert(issues.length>0);
assert(boschDistancePayload(payload(12,4)).issue);assert(boschDistancePayload(payload(12,8)).issue);assert(boschDistancePayload(payload(NaN)).issue);assert(boschDistancePayload(payload(0)).issue);assert(boschDistancePayload(payload(151)).issue);assert(boschDistancePayload(payload(.08)).metres);assert(boschDistancePayload(payload(3,1,1,1)).ignored);
class Events{constructor(){this.listeners=new Map()}addEventListener(k,f){this.listeners.set(k,f)}removeEventListener(k,f){if(this.listeners.get(k)===f)this.listeners.delete(k)}emit(k,e){this.listeners.get(k)?.(e)}}
const characteristic=new Events();characteristic.properties={write:true,indicate:true};characteristic.startNotifications=async()=>characteristic;const writes=[];characteristic.writeValueWithResponse=async b=>{writes.push(Array.from(b));const ack=Uint8Array.of(0,0,0x82);characteristic.emit('characteristicvaluechanged',{target:{value:new DataView(ack.buffer)}})};
const device=new Events();device.name='Bosch GLM 150 C';device.gatt={connected:false,async connect(){this.connected=true;return {getPrimaryService:async uuid=>{if(uuid!==BOSCH_BLE_PROFILES[1].service){const e=Error('not found');e.name='NotFoundError';throw e}return {getCharacteristic:async uuid=>{assert.equal(uuid,BOSCH_BLE_PROFILES[1].characteristic);return characteristic}}}}},disconnect(){this.connected=false}};
const states=[],values=[],logs=[];const bluetooth={async requestDevice(options){assert(options.optionalServices.includes(BOSCH_BLE_PROFILES[0].service));assert(options.optionalServices.includes(BOSCH_BLE_PROFILES[1].service));return device}};
(async()=>{const link=new BoschDistanceLink({bluetooth,secure:true,onState:(...a)=>states.push(a),onDistance:v=>values.push(v),onLog:s=>logs.push(s)});await link.connect();assert(link.ready);assert.equal(states.at(-1)[0],'connected');assert.deepEqual(writes[0],[0xc0,0x55,2,1,0,0x1a]);function notify(b){characteristic.emit('characteristicvaluechanged',{target:{value:new DataView(b.buffer)}})}notify(measured);notify(measured);assert.equal(values.length,1);notify(frame(payload(12,4)));assert.equal(values.length,1);assert.equal(states.at(-1)[0],'connected');notify(frame(payload(5,1,0x1235)));assert.equal(values.length,2);await link.disconnect();assert(!link.ready);assert(!device.gatt.connected);assert(!characteristic.listeners.size);assert.deepEqual(writes.at(-1),[0xc0,0x55,2,0,0,0x62]);await link.connect();assert(link.ready);device.gatt.connected=false;device.emit('gattserverdisconnected');assert(!link.ready);assert.equal(states.at(-1)[0],'disconnected');
let unsupported;await new BoschDistanceLink({bluetooth:null,secure:true,onState:s=>unsupported=s,onDistance(){},onLog(){}}).connect();assert.equal(unsupported,'unsupported');console.log('Protocol: CRC, fragments, endian, invalid measurements, duplicate events, two profiles, connect/disconnect/reconnect, unsupported browser passed');})().catch(e=>{console.error(e);process.exitCode=1});

// Replay the actual calculated-length packets from the user's GLM 150 C log.
for(const [hex,expected,id] of [
 ['c0 55 10 2e 00 d0 03 71 8c ef 3e 40 13 f1 3e ab 95 bb 40 e6',0.4678683578968048,976],
 ['c0 55 10 2e 00 d1 03 b6 0f ef 3e 1b 0d f0 3e 12 97 93 40 ca',0.4669167399406433,977]
]){const b=Uint8Array.from(hex.split(' ').map(x=>parseInt(x,16)));let result;const r=new BoschFrameReader(f=>result=boschDistancePayload(f.payload),e=>{throw Error(e)});r.push(new DataView(b.buffer));assert.equal(result.metres,expected);assert.equal(result.id,id);assert.equal(result.mode,11)}
assert(boschDistancePayload(payload(3,11,1,1)).ignored);
assert(boschDistancePayload(payload(NaN,11)).issue);
assert(boschDistancePayload(payload(3,60)).issue);
console.log('Actual indirect packets: result field, CRC, mode, laser-on exclusion and unknown-mode rejection passed');